/**
 * DEEP property / fuzz tests — money-path INVARIANTS.
 *
 * These are NOT example-based tests. Each `it` loops over hundreds of random
 * + boundary inputs generated by a SEEDED PRNG (mulberry32) so the suite is
 * fully deterministic (same seed → same inputs every run), yet still exercises
 * a wide, adversarial input space.
 *
 * The functions under test are the PURE money helpers that the compose /
 * orchestrate / x402 money path is built on:
 *
 *   - parseUnits(amountUsd.toFixed(decimals), decimals)  ← the exact pattern in
 *       src/adapters/{avalanche,base,kite-ozone}/payment.ts quote() and
 *       src/lib/downstream-payment.ts (per-chain atomic scaling, 6 vs 18 dec).
 *   - usdcToWei18 = BigInt(Math.round(usd * 1e6)) * BigInt(1e12)  ← the exact
 *       18-dec scaling in src/services/compose.ts:792 and
 *       src/services/fee-charge.ts:126 (feeUsdcToWei).
 *   - protocol-fee composition  total = pipelineUsd * (1 + rate), 6dp  ← the
 *       exact x402-challenge math in src/routes/compose.ts:130
 *       (augmentX402ChallengeAmount) and chargeProtocolFee fee = budget*rate.
 *   - getProtocolFeeRate() env guard  ← src/services/fee-charge.ts.
 *   - pyusdWeiToUsd / getPyusdUsdRate  ← src/lib/price.ts.
 *
 * The INVARIANTS asserted here are the ones that must hold for EVERY finite
 * input: conservation (fee+net==total), no negative / NaN / Infinity money,
 * monotonicity (more steps / higher price ⇒ challenge never decreases),
 * correct decimals per chain, parseUnits never throws on any finite price
 * (incl. dust 1e-7 / many-decimal / scientific-notation-prone), bounded
 * rounding (≤ 1 atomic unit) in the documented direction, and — the headline
 * money-safety invariant — the x402 challenge ALWAYS >= the real pipeline
 * cost (never undercharge).
 */

import { parseUnits } from 'viem';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { getProtocolFeeRate } from '../services/fee-charge.js';
import { getPyusdUsdRate, pyusdWeiToUsd } from './price.js';
import { PLACEHOLDER_FEE_USD } from './pricing-constants.js';

// ── Seeded PRNG (mulberry32) — deterministic across runs ────────────────────
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const SEED = 0x5eed1234;
const ITERATIONS = 400;

/** Random USD price in [lo, hi] with up to `decimals` fractional digits. */
function randPrice(
  rng: () => number,
  lo: number,
  hi: number,
  decimals = 6,
): number {
  const raw = lo + rng() * (hi - lo);
  const scale = 10 ** Math.floor(rng() * (decimals + 1));
  return Math.round(raw * scale) / scale;
}

// ── The money helpers under test (mirror production EXACTLY) ────────────────

/** 18-dec scaling used by compose.ts:792 + fee-charge.ts:126 (feeUsdcToWei). */
function usdcToWei18(usd: number): bigint {
  return BigInt(Math.round(usd * 1e6)) * BigInt(1e12);
}

/** Adapter quote() pattern: parseUnits(usd.toFixed(decimals), decimals). */
function quoteAtomic(usd: number, decimals: number): bigint {
  return parseUnits(usd.toFixed(decimals), decimals);
}

/** x402 challenge math from augmentX402ChallengeAmount (route compose.ts:130). */
function composeChallengeUsd(stepPrices: number[], rate: number): number {
  let pipelineUsd = 0;
  for (const p of stepPrices) {
    const valid = typeof p === 'number' && p > 0 && !Number.isNaN(p);
    pipelineUsd += valid ? p : PLACEHOLDER_FEE_USD;
  }
  if (pipelineUsd <= 0) return 0;
  const total = Number((pipelineUsd * (1 + rate)).toFixed(6));
  if (total <= 0) return pipelineUsd > 0 ? 0.000001 : 0;
  return total;
}

// Boundary prices that must be covered explicitly every run.
const BOUNDARY_PRICES = [
  0, // free / config-miss
  1e-7, // sub-atomic dust (scientific-notation-prone)
  1e-6, // exactly 1 atomic unit (6dp)
  0.0000005, // round-half boundary at 6dp
  0.0000015, // round-half boundary at 6dp
  0.000001, // exactly-6-decimal
  0.123456, // exactly-6-decimal
  0.1234567, // > 6 decimals
  0.123456789012, // many-decimal
  1, // unit
  9.99, // typical
  999.999999, // large realistic
  1_000_000, // max realistic price
];

describe('money-path FUZZ — parseUnits per-chain atomic scaling (6 vs 18 dec)', () => {
  it('never throws on any finite price (dust / many-decimal / sci-notation) for 6 & 18 dec', () => {
    const rng = mulberry32(SEED);
    const samples = [...BOUNDARY_PRICES];
    for (let i = 0; i < ITERATIONS; i++) {
      // mix of dust, normal, large, and high-precision prices.
      const bucket = i % 4;
      if (bucket === 0) samples.push(randPrice(rng, 0, 1e-6, 12)); // dust
      else if (bucket === 1) samples.push(randPrice(rng, 1e-6, 10, 12)); // normal hi-prec
      else if (bucket === 2) samples.push(randPrice(rng, 10, 1_000_000, 6)); // large
      else samples.push(rng() * 1e-7); // raw sub-atomic (sci-notation prone)
    }

    for (const usd of samples) {
      for (const decimals of [6, 18]) {
        // INVARIANT: parseUnits never throws on a finite price via toFixed().
        let atomic = 0n;
        expect(() => {
          atomic = quoteAtomic(usd, decimals);
        }).not.toThrow();
        // INVARIANT: no negative atomic value.
        expect(atomic >= 0n).toBe(true);
      }
    }
  });

  it('6-dec and 18-dec encode the SAME USD value within float-toFixed slack (documented asymmetry)', () => {
    const rng = mulberry32(SEED ^ 0x11);
    // FINDING (fuzz-surfaced, 2026-06-29): the 18-dec quote path
    // `parseUnits(usd.toFixed(18), 18)` (kite-ozone/payment.ts:382, PYUSD 18-dec)
    // is NOT byte-identical to the 6-dec path scaled by 1e12. Reason: a 6dp-grid
    // price like 978.18 is not exactly representable in float64, so
    // (978.18).toFixed(18) === "978.179999999999949978" → parseUnits yields
    // 978179999999999949978, ~50022 wei OFF from 978180000000000000000. The
    // 6-dec compose `valueWei` path uses Math.round(usd*1e6)*1e12 which snaps to
    // the clean 6dp grid. The 18-dec divergence is BIDIRECTIONAL (the float's
    // nearest representation can sit just above or just below the decimal) and
    // bounded by < 1e6 wei (sub atomic-6dp, ≈1e-12 USD) — negligible vs one 6dp
    // atomic unit (1e12 wei) but real. The correct invariant is bounded
    // equality, not exact equality.
    const ONE_6DP_ATOMIC_IN_18DEC = BigInt(1e12); // 1 unit on the 6dp grid in 18-dec
    for (let i = 0; i < ITERATIONS; i++) {
      const usd = randPrice(rng, 0, 1000, 6);
      const a6 = quoteAtomic(usd, 6);
      const a18 = quoteAtomic(usd, 18);
      const expected = a6 * BigInt(1e12);
      const delta = a18 > expected ? a18 - expected : expected - a18;
      // INVARIANT: decimals correct per chain within float-toFixed slack — the
      // two encodings never diverge by as much as one 6dp atomic unit (1e12 wei).
      expect(delta < ONE_6DP_ATOMIC_IN_18DEC).toBe(true);
    }
  });

  it('rounding is bounded by <= 1 atomic unit of the target grid', () => {
    const rng = mulberry32(SEED ^ 0x22);
    for (let i = 0; i < ITERATIONS; i++) {
      const usd = Math.max(0, randPrice(rng, 0, 100, 12)); // high-precision input
      for (const decimals of [6, 18]) {
        const atomic = quoteAtomic(usd, decimals);
        const exact = usd * 10 ** decimals;
        // INVARIANT: |atomic - exact| <= 1 atomic unit (toFixed round-half).
        const diff = Math.abs(Number(atomic) - exact);
        expect(diff).toBeLessThanOrEqual(1 + 1e-3); // float slack
      }
    }
  });
});

describe('money-path FUZZ — 18-dec scaling (compose valueWei / feeUsdcToWei)', () => {
  it('usdcToWei18 is non-negative, finite-string, and monotonic in price', () => {
    const rng = mulberry32(SEED ^ 0x33);
    let prev = -1n;
    const sorted: number[] = [];
    for (let i = 0; i < ITERATIONS; i++) sorted.push(randPrice(rng, 0, 1000, 6));
    sorted.sort((a, b) => a - b);

    for (const usd of sorted) {
      const wei = usdcToWei18(usd);
      // INVARIANT: never negative.
      expect(wei >= 0n).toBe(true);
      // INVARIANT: monotonic — higher price ⇒ >= wei.
      expect(wei >= prev).toBe(true);
      prev = wei;
      // INVARIANT: round-trip back to USD within 1 atomic-6dp unit.
      const backUsd = Number(wei / BigInt(1e12)) / 1e6;
      expect(Math.abs(backUsd - usd)).toBeLessThanOrEqual(1e-6 + 1e-9);
    }
  });

  it('compose valueWei == fee-charge feeUsdcToWei for the same amount (single convention)', () => {
    const rng = mulberry32(SEED ^ 0x44);
    const samples = [...BOUNDARY_PRICES.filter((p) => p <= 1_000_000)];
    for (let i = 0; i < ITERATIONS; i++) samples.push(randPrice(rng, 0, 1000, 9));
    for (const usd of samples) {
      // compose.ts:792 and fee-charge.ts:126 MUST agree byte-for-byte.
      const composeWei = String(usdcToWei18(usd));
      const feeWei = String(BigInt(Math.round(usd * 1e6)) * BigInt(1e12));
      expect(composeWei).toBe(feeWei);
    }
  });
});

describe('money-path FUZZ — protocol fee composition & conservation', () => {
  it('fee + net == total (conservation), fee in [0,total], no NaN/Infinity', () => {
    const rng = mulberry32(SEED ^ 0x55);
    for (let i = 0; i < ITERATIONS; i++) {
      const budget = randPrice(rng, 1e-6, 100_000, 6);
      const rate = rng() * 0.1; // valid PROTOCOL_FEE_RATE domain [0, 0.10]
      // mirror chargeProtocolFee: fee = round6(budget*rate)
      const fee = Number((budget * rate).toFixed(6));
      const net = Number((budget - fee).toFixed(6));
      // INVARIANT: no NaN / Infinity.
      expect(Number.isFinite(fee)).toBe(true);
      expect(Number.isFinite(net)).toBe(true);
      // INVARIANT: no negative money.
      expect(fee).toBeGreaterThanOrEqual(0);
      expect(net).toBeGreaterThanOrEqual(0);
      // INVARIANT: fee never exceeds the budget (the safety guard in
      // chargeProtocolFee throws ProtocolFeeError otherwise).
      expect(fee).toBeLessThanOrEqual(budget + 1e-9);
      // INVARIANT: conservation — fee + net reconstructs total within 1 atomic.
      expect(Math.abs(fee + net - budget)).toBeLessThanOrEqual(1e-6 + 1e-9);
    }
  });
});

describe('money-path FUZZ — x402 challenge never undercharges the pipeline', () => {
  it('challenge >= sum(stepPrices) and >= step count * placeholder for invalid steps', () => {
    const rng = mulberry32(SEED ^ 0x66);
    for (let i = 0; i < ITERATIONS; i++) {
      const n = 1 + Math.floor(rng() * 8); // 1..8 steps
      const prices: number[] = [];
      let realCost = 0;
      for (let s = 0; s < n; s++) {
        // ~30% of steps are "malformed/invalid" (0, NaN, negative) → placeholder.
        const malformed = rng() < 0.3;
        const choices = [0, Number.NaN, -1];
        const p = malformed
          ? choices[Math.floor(rng() * 3)]!
          : randPrice(rng, 1e-6, 500, 6);
        prices.push(p);
        const valid = typeof p === 'number' && p > 0 && !Number.isNaN(p);
        realCost += valid ? p : PLACEHOLDER_FEE_USD;
      }
      const rate = rng() * 0.1;
      const challenge = composeChallengeUsd(prices, rate);

      // INVARIANT: never NaN / Infinity / negative.
      expect(Number.isFinite(challenge)).toBe(true);
      expect(challenge).toBeGreaterThanOrEqual(0);
      // INVARIANT (HEADLINE): challenge >= real pipeline cost — NEVER undercharge.
      // (rate >= 0 makes the fee additive; rounding floor protects sub-atomic.)
      expect(challenge).toBeGreaterThanOrEqual(realCost - 1e-9);
      // INVARIANT: a malformed step is over-estimated, not under-charged: the
      // challenge for a pipeline with >=1 step is always strictly positive.
      expect(challenge).toBeGreaterThan(0);
    }
  });

  it('monotonic: appending a step (or raising a price) never lowers the challenge', () => {
    const rng = mulberry32(SEED ^ 0x77);
    for (let i = 0; i < ITERATIONS; i++) {
      const rate = rng() * 0.1;
      const base: number[] = [];
      const n = 1 + Math.floor(rng() * 5);
      for (let s = 0; s < n; s++) base.push(randPrice(rng, 1e-6, 100, 6));

      const cBase = composeChallengeUsd(base, rate);

      // (a) appending a positive-priced step never lowers the challenge.
      const extra = randPrice(rng, 1e-6, 100, 6);
      const cMoreSteps = composeChallengeUsd([...base, extra], rate);
      expect(cMoreSteps).toBeGreaterThanOrEqual(cBase - 1e-9);

      // (b) raising any single price never lowers the challenge.
      const idx = Math.floor(rng() * base.length);
      const raised = [...base];
      raised[idx] = raised[idx]! + randPrice(rng, 1e-6, 100, 6);
      const cRaised = composeChallengeUsd(raised, rate);
      expect(cRaised).toBeGreaterThanOrEqual(cBase - 1e-9);
    }
  });

  it('boundary step-counts: empty=0, 1 step, 5 steps, many steps all behave', () => {
    const rate = 0.01;
    // empty pipeline → 0 (no challenge).
    expect(composeChallengeUsd([], rate)).toBe(0);
    // 1 valid step.
    expect(composeChallengeUsd([0.5], rate)).toBeGreaterThanOrEqual(0.5);
    // all-invalid steps → each over-estimated to placeholder, summed.
    const allInvalid = composeChallengeUsd([0, Number.NaN, -1, 0, 0], rate);
    expect(allInvalid).toBeGreaterThanOrEqual(5 * PLACEHOLDER_FEE_USD);
    // many tiny steps: 50 dust steps still charge >= sum and stay finite.
    const dust = Array.from({ length: 50 }, () => 1e-6);
    const cDust = composeChallengeUsd(dust, rate);
    expect(Number.isFinite(cDust)).toBe(true);
    expect(cDust).toBeGreaterThanOrEqual(50 * 1e-6 - 1e-9);
  });
});

describe('money-path FUZZ — env-guarded rate / pyusd conversions', () => {
  const ORIG = { ...process.env };
  beforeEach(() => {
    delete process.env.PROTOCOL_FEE_RATE;
    delete process.env.PYUSD_USD_RATE;
  });
  afterEach(() => {
    process.env = { ...ORIG };
  });

  it('getProtocolFeeRate always returns a finite rate in [0, 0.10] for ANY env string', () => {
    const rng = mulberry32(SEED ^ 0x88);
    const malformed = [
      '',
      'abc',
      'NaN',
      'Infinity',
      '-Infinity',
      '-0.5',
      '0.2',
      '999',
      '1e9',
      '0x10',
    ];
    const samples = [...malformed];
    for (let i = 0; i < ITERATIONS; i++) {
      // random strings incl. valid + wildly out-of-range.
      samples.push(String((rng() - 0.5) * 1e6));
    }
    for (const raw of samples) {
      process.env.PROTOCOL_FEE_RATE = raw;
      const rate = getProtocolFeeRate();
      // INVARIANT: never NaN/Infinity, always within the documented domain.
      expect(Number.isFinite(rate)).toBe(true);
      expect(rate).toBeGreaterThanOrEqual(0);
      expect(rate).toBeLessThanOrEqual(0.1);
    }
  });

  it('pyusdWeiToUsd: no negative output, no NaN, monotonic, Infinity only on overflow', () => {
    const rng = mulberry32(SEED ^ 0x99);
    delete process.env.PYUSD_USD_RATE; // rate 1.0
    expect(getPyusdUsdRate()).toBe(1.0);

    // negative wei → clamped to 0 (defensive).
    expect(pyusdWeiToUsd(-1n)).toBe(0);
    expect(pyusdWeiToUsd(-999999999n)).toBe(0);
    // overflow beyond MAX_SAFE_INTEGER → +Infinity (documented, no throw).
    expect(pyusdWeiToUsd(BigInt(Number.MAX_SAFE_INTEGER) + 1n)).toBe(
      Number.POSITIVE_INFINITY,
    );

    let prev = -1;
    const weis: bigint[] = [];
    for (let i = 0; i < ITERATIONS; i++) {
      weis.push(BigInt(Math.floor(rng() * 1e12)));
    }
    weis.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
    for (const wei of weis) {
      const usd = pyusdWeiToUsd(wei);
      // INVARIANT: no NaN, never negative, monotonic non-decreasing.
      expect(Number.isNaN(usd)).toBe(false);
      expect(usd).toBeGreaterThanOrEqual(0);
      expect(usd).toBeGreaterThanOrEqual(prev - 1e-9);
      prev = usd;
    }
  });
});
