/**
 * Auth Routes — shared parsers, validators and request helpers.
 *
 * Pure reorganization of `src/routes/auth.ts` (refactor B2, 2026-06-24): this
 * module hosts the module-level helpers that were previously private to the
 * god-file so the per-domain sub-plugins can import them. Logic is UNCHANGED.
 */

import crypto from 'node:crypto';
import type { FastifyRequest } from 'fastify';
import { resolveEscrowContract } from '../../adapters/escrow-verifier.js';
import type { ChainKey } from '../../adapters/types.js';
import {
  identityService,
  isIdentityVerified,
} from '../../services/identity.js';
import type {
  A2AAgentKeyRow,
  CreateKeySessionInput,
  DelegationPolicy,
  DelegationTypedData,
  SpendPolicyInput,
  SpendPolicyWindowType,
} from '../../types/index.js';

// ── Funding-wallet binding (WKH-35 FIX-1) ───────────────────

export const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;

/**
 * Canonical message a caller must sign to prove control of a funding wallet.
 * FIXED prefix + the caller's authenticated `key_id` (NEVER from the body) so
 * the proof is bound to a specific key and cannot be replayed across keys.
 */
export function fundingWalletBindMessage(keyId: string): string {
  return `WASIAI_BIND_FUNDING_WALLET:${keyId}`;
}

// ── ERC-8004 identity binding input validation (WKH-100, DT-14) ──────────────

const TOKEN_ID_RE = /^[0-9]+$/;
const UINT256_MAX = (1n << 256n) - 1n;

/**
 * Parse + validate a token_id into a `bigint` without precision loss (CD-11).
 * Accepts a decimal string or a non-negative integer number; rejects empty,
 * non-numeric, negative or `> 2^256-1`. Returns `null` on any rejection.
 * NEVER uses `Number()` on the token_id (CD-11).
 */
export function parseTokenId(raw: unknown): bigint | null {
  let s: string;
  if (typeof raw === 'string') s = raw.trim();
  else if (typeof raw === 'number' && Number.isInteger(raw) && raw >= 0)
    s = String(raw);
  else return null;
  if (s === '' || !TOKEN_ID_RE.test(s)) return null;
  let v: bigint;
  try {
    v = BigInt(s);
  } catch {
    return null;
  }
  if (v < 0n || v > UINT256_MAX) return null;
  return v;
}

export const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,127}$/;
// WKH-100 FIX v3 (DT-23 / BLQ-MED-1): the bind anchor is the registry PK `id`
// (canonical, immutable, generated by `name.toLowerCase().replace(/\s+/g,'-')`),
// NOT the mutable display name. Validate against the PK shape (same form as
// SLUG_RE) so divergent normalizations can no longer collide into the same
// token. Existence is re-checked against the `registries` table below.
export const REGISTRY_ID_RE = /^[a-z0-9][a-z0-9-]{0,127}$/;

/**
 * Flag opt-in del escrow no-custodial (WKH-126b, CD-11). Comparación de string
 * ESTRICTA: solo `'true'` exacto activa el flujo escrow; cualquier otro valor
 * (incl. `'1'`, `'TRUE'`, `''`, `undefined`) → flag OFF = treasury (default,
 * fail-safe, AC-8). PROHIBIDO `Boolean(process.env.ESCROW_MODE_ENABLED)`.
 */
function escrowModeEnabled(): boolean {
  return process.env.ESCROW_MODE_ENABLED === 'true';
}

/**
 * Routing escrow POR-CADENA (WKH-126c). El contrato escrow es per-cadena
 * (`A2A_ESCROW_CONTRACT_<FAMILY>`), pero el flag `ESCROW_MODE_ENABLED` es
 * global. El escrow solo aplica si AMBOS se cumplen: flag global on Y contrato
 * configurado para esa cadena. Cadenas sin contrato → fallback silencioso a
 * treasury (no 503 ESCROW_CONTRACT_NOT_CONFIGURED). Flag off → false siempre
 * (CD-2), preservando AC-8 de WKH-126b (treasury en el 100% de las cadenas).
 */
export function escrowEnabledForChain(chainKey: ChainKey): boolean {
  return escrowModeEnabled() && resolveEscrowContract(chainKey) !== null;
}

// ── Helper: resolve caller key from x-a2a-key header ────────

export async function resolveCallerKey(
  request: FastifyRequest,
): Promise<A2AAgentKeyRow | null> {
  // DT-2 (WKH-BEARER-FIX): Priority order: x-a2a-key > Bearer wasi_a2a_* > null
  let rawKey: string | undefined;

  const headerValue = request.headers['x-a2a-key'];
  if (headerValue && typeof headerValue === 'string') {
    rawKey = headerValue;
  } else {
    // DT-1/DT-3: case-insensitive scheme, case-sensitive prefix (same as a2a-key.ts:86-93)
    const authHeader = request.headers.authorization;
    if (authHeader && typeof authHeader === 'string') {
      const match = /^bearer\s+(.+)$/i.exec(authHeader);
      if (match?.[1].startsWith('wasi_a2a_')) {
        rawKey = match[1];
      }
    }
  }

  if (!rawKey) return null;

  const keyHash = crypto.createHash('sha256').update(rawKey).digest('hex');
  const callerKey = await identityService.lookupByHash(keyHash);
  if (callerKey) {
    // WKH-100 (AC-6/DT-17): derived transient flag, no RPC.
    callerKey.erc8004_verified = isIdentityVerified(callerKey);
  }
  return callerKey;
}

// ── Helper: extract the raw authenticator key from the request ──
// WKH-101: same precedence as resolveCallerKey (x-a2a-key > Bearer wasi_a2a_*).
// Used to detect a `wasi_a2a_session_*` authenticator (sub-delegation, AC-15)
// BEFORE resolveCallerKey (which would return null for a session token, losing
// the exact DELEGATION_NOT_ALLOWED code).
export function rawKeyFromRequest(request: FastifyRequest): string | undefined {
  const headerValue = request.headers['x-a2a-key'];
  if (headerValue && typeof headerValue === 'string') {
    return headerValue;
  }
  const authHeader = request.headers.authorization;
  if (authHeader && typeof authHeader === 'string') {
    const match = /^bearer\s+(.+)$/i.exec(authHeader);
    if (match?.[1].startsWith('wasi_a2a_')) {
      return match[1];
    }
  }
  return undefined;
}

// ── WKH-101: delegation input validation (DT-1, CD-3) ───────────

export const SESSION_TOKEN_PREFIX = 'wasi_a2a_session_';

// CR-MNR-1 (WKH-101): los límites de la policy deben ser decimales positivos.
// Sin esto, un "-5" o "abc" pasaba la validación de shape y producía una
// delegación inútil que recién fallaba (503) en el débito. Se rechaza acá.
const POSITIVE_DECIMAL_RE = /^\d+(\.\d+)?$/;

/** `true` si `v` es un decimal `> 0` (string canónico, sin signo ni notación). */
function isPositiveDecimalAmount(v: string): boolean {
  if (!POSITIVE_DECIMAL_RE.test(v)) return false;
  return Number.parseFloat(v) > 0;
}

/** Valida + tipa la policy del request. Devuelve null si el shape es inválido. */
export function parseDelegationPolicy(raw: unknown): DelegationPolicy | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const p = raw as Record<string, unknown>;
  if (
    typeof p.max_amount_per_tx !== 'string' ||
    typeof p.max_total_amount !== 'string' ||
    typeof p.expires_at !== 'number' ||
    !Number.isFinite(p.expires_at)
  ) {
    return null;
  }
  // CR-MNR-1: max_amount_per_tx / max_total_amount deben ser decimales > 0.
  if (
    !isPositiveDecimalAmount(p.max_amount_per_tx) ||
    !isPositiveDecimalAmount(p.max_total_amount)
  ) {
    return null;
  }
  if (
    !Array.isArray(p.allowed_chains) ||
    !p.allowed_chains.every((c) => typeof c === 'number') ||
    !Array.isArray(p.allowed_agent_slugs) ||
    !p.allowed_agent_slugs.every((s) => typeof s === 'string') ||
    !Array.isArray(p.allowed_registries) ||
    !p.allowed_registries.every((s) => typeof s === 'string')
  ) {
    return null;
  }
  return {
    max_amount_per_tx: p.max_amount_per_tx,
    max_total_amount: p.max_total_amount,
    expires_at: p.expires_at,
    allowed_chains: p.allowed_chains as number[],
    allowed_agent_slugs: p.allowed_agent_slugs as string[],
    allowed_registries: p.allowed_registries as string[],
  };
}

/** Valida + tipa el typed-data del request (primaryType==='Delegation'). */
export function parseDelegationTypedData(
  raw: unknown,
): DelegationTypedData | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const td = raw as Record<string, unknown>;
  if (
    typeof td.domain !== 'object' ||
    td.domain === null ||
    typeof td.types !== 'object' ||
    td.types === null ||
    td.primaryType !== 'Delegation' ||
    typeof td.message !== 'object' ||
    td.message === null
  ) {
    return null;
  }
  const domain = td.domain as Record<string, unknown>;
  if (
    typeof domain.name !== 'string' ||
    typeof domain.version !== 'string' ||
    typeof domain.chainId !== 'number'
  ) {
    return null;
  }
  const message = td.message as Record<string, unknown>;
  if (
    typeof message.session_key !== 'string' ||
    !ADDRESS_RE.test(message.session_key) ||
    typeof message.nonce !== 'string'
  ) {
    return null;
  }
  // La policy del message debe ser un objeto válido (la igualdad con
  // input.policy la verifica el service vía policiesEqual, CD-3).
  const msgPolicy = parseDelegationPolicy(message.policy);
  if (!msgPolicy) return null;

  return {
    domain: {
      name: domain.name,
      version: domain.version,
      chainId: domain.chainId,
    },
    types: td.types as DelegationTypedData['types'],
    primaryType: 'Delegation',
    message: {
      session_key: message.session_key as `0x${string}`,
      policy: msgPolicy,
      nonce: message.nonce as `0x${string}`,
    },
  };
}

// ── WKH-121: key-session input validation (CD-AB-3) ─────────────

export const KEY_SESSION_TOKEN_PREFIX = 'wasi_a2a_sess_';

/**
 * Valida + tipa el body del POST /auth/key-session. Devuelve null si el shape o
 * los tipos son inválidos. La validación semántica fina de rango (ttl/budget) y
 * scope ⊆ padre la hace el service (mapea a INVALID_INPUT / SCOPE_EXCEEDS_PARENT).
 * `max_budget_usd` se acepta como string o number y se normaliza a string canónico.
 */
export function parseCreateKeySessionInput(
  raw: unknown,
): CreateKeySessionInput | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const b = raw as Record<string, unknown>;

  // ttl_seconds: entero (la cota de rango la valida el service).
  if (typeof b.ttl_seconds !== 'number' || !Number.isInteger(b.ttl_seconds)) {
    return null;
  }

  // max_budget_usd: string o number → string (sin pérdida; el service valida > 0).
  let maxBudget: string;
  if (typeof b.max_budget_usd === 'string') {
    maxBudget = b.max_budget_usd;
  } else if (
    typeof b.max_budget_usd === 'number' &&
    Number.isFinite(b.max_budget_usd)
  ) {
    maxBudget = String(b.max_budget_usd);
  } else {
    return null;
  }

  // allowed_*: opcionales; si presentes, deben ser string[].
  const parseList = (v: unknown): string[] | null | undefined => {
    if (v === undefined) return undefined;
    if (Array.isArray(v) && v.every((s) => typeof s === 'string')) {
      return v as string[];
    }
    return null; // presente pero inválido
  };

  const registries = parseList(b.allowed_registries);
  const slugs = parseList(b.allowed_agent_slugs);
  const categories = parseList(b.allowed_categories);
  if (registries === null || slugs === null || categories === null) {
    return null;
  }

  // WKH-123: require_signature opcional; si presente DEBE ser boolean.
  if (
    b.require_signature !== undefined &&
    typeof b.require_signature !== 'boolean'
  ) {
    return null;
  }

  const input: CreateKeySessionInput = {
    ttl_seconds: b.ttl_seconds,
    max_budget_usd: maxBudget,
  };
  if (registries !== undefined) input.allowed_registries = registries;
  if (slugs !== undefined) input.allowed_agent_slugs = slugs;
  if (categories !== undefined) input.allowed_categories = categories;
  if (b.require_signature !== undefined) {
    input.require_signature = b.require_signature;
  }
  return input;
}

/**
 * WKH-125: shape validation del body de PUT /auth/keys/me/spend-policies.
 * Acepta `window` o `window_type` (alias) para el tipo de ventana. La
 * normalización del destino + el invariante de ventana los valida el service
 * (`spend-policy.ts`, CD-6). Acá sólo el shape (CD-AB-3).
 */
export function parseSpendPolicyInput(raw: unknown): SpendPolicyInput | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const b = raw as Record<string, unknown>;

  if (typeof b.destination !== 'string' || b.destination.trim() === '') {
    return null;
  }

  // max_usd: string o number → string (sin pérdida; el service valida formato).
  let maxUsd: string;
  if (typeof b.max_usd === 'string') {
    maxUsd = b.max_usd;
  } else if (typeof b.max_usd === 'number' && Number.isFinite(b.max_usd)) {
    maxUsd = String(b.max_usd);
  } else {
    return null;
  }

  // window_type (o alias `window`): 'total' | 'rolling'.
  const rawWindow = b.window_type ?? b.window;
  if (rawWindow !== 'total' && rawWindow !== 'rolling') {
    return null;
  }
  const windowType = rawWindow as SpendPolicyWindowType;

  // window_secs: opcional; si presente DEBE ser int (el service valida el
  // invariante total⇒null / rolling⇒>0).
  let windowSecs: number | null | undefined;
  if (b.window_secs === undefined || b.window_secs === null) {
    windowSecs = b.window_secs as null | undefined;
  } else if (
    typeof b.window_secs === 'number' &&
    Number.isInteger(b.window_secs)
  ) {
    windowSecs = b.window_secs;
  } else {
    return null;
  }

  const input: SpendPolicyInput = {
    destination: b.destination,
    max_usd: maxUsd,
    window_type: windowType,
  };
  if (windowSecs !== undefined) input.window_secs = windowSecs;
  return input;
}
